name: Build new image

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: ${{ github.ref_name }}
        type: string
      is_scheduled:
        description: 'Is this a scheduled build?'
        required: false
        default: false
        type: boolean

env:
  cidata: .ci
  appname: remote-debian-base
  dockerfile: Dockerfile

jobs:

  release:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    outputs:
      last_version: ${{ steps.last_versions.outputs.last_version }}
      last_hash: ${{ steps.last_versions.outputs.last_hash }}
      new_version: ${{ steps.new_version.outputs.new_version }}


    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}

    - name: Determine last version details
      id: last_versions
      run: |
        last_version=$(cat ${{ env.cidata }}/release_version.txt)
        last_hash=$(cat ${{ env.cidata }}/release_hash.txt)
        echo "last_version=$last_version" >> "$GITHUB_OUTPUT"
        echo "last_hash=$last_hash" >> "$GITHUB_OUTPUT"

    - name: Determine new version
      id: new_version
      uses: TLii/workflows/.github/workflows/versioning.yml@master
      with:
        last_build_head: ${{ steps.last_versions.outputs.last_hash }}
        current_version: ${{ steps.last_versions.outputs.last_version }}
        use_build_numbers: false


  build:
    runs-on: ubuntu-latest

    steps:

    - name: Code checkout
      uses: actions/checkout@v3

    - name: Determine tags
      run: |

        new_version=${{ steps.release.outputs.new_version }}
        branch=${{ inputs.branch }}
        is_release=${{ inputs.is_release }}
        is_scheduled=${{ inputs.is_scheduled }}

        tags="$branch-latest, $branch, $new_version, ${{ env.github_hash }}, ${{ github.sha }}

        if [[ ${{ env.branch }} == 'master' ]]); then
          tags+="latest"
          addlatest="true"
        else
          addlatest="false"
        fi
        echo "tags=$(echo "$tags"|sed 's/[, ]*$//g')" >> "$GITHUB_ENV"
        echo "addlatest=$addlatest" >> "$GITHUB_ENV"

    - name: Build and push container image
      uses: mr-smithers-excellent/docker-build-push@v6.2
      with:
        image: remote-ide/${{ env.appname }}
        tags: ${{ env.tags }}
        registry: ${{ secrets.REGISTRY_URL }}
        dockerfile: ${{ env.dockerfile }}
        username: ${{ secrets.REGISTRY_USER }} # optional
        password: ${{ secrets.REGISTRY_PASSWORD }} # optional
        addLatest: ${{ env.addlatest }}

    - name: Record new version
      run: |
        echo "${{ steps.new_version.outputs.new_version }}" > ${{ env.cidata }}/release_version.txt
        echo "${{ github.sha }}" > ${{ env.cidata }}/release_hash.txt

    - name: Commit changed version number and changed ci values
      id: commit
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git add .
        if [[ -z "$(git status --porcelain)" ]]; then
          # If no files were changed, there's nothing to push.
          echo "push_needed=false" >> "$GITHUB_OUTPUT"
        else
          # If files were changed, record the change.
          git commit -m "chore: Automatic version update" -a
          echo "push_needed=true" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - name: Push changed version commit
      if: ${{ steps.commit.outputs.push_needed == 'true' }}
      id: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
