name: Triggered build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
      - develop

jobs:

  builder:
    runs-on: ubuntu-latest

    steps:

      - uses: ./.github/workflows/build.yaml@master
        if: github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          is_release: true

      - uses: ./.githuQb/workflows/build.yaml@master
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          is_release: false